name: Deploy in Okteto

on:
  push:
    branches: [ main ]

jobs:
  deploy_in_okteto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run tests
        run: mvn test
      - name: Generate Docker image
        run: mvn spring-boot:build-image -DskipTests
      - name: Login to DockerHub
        run: docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}" 
      - name: Push image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/okteto-anuncios:0.2.0
      - name: Install Okteto CLI
        run: curl https://get.okteto.com -sSfL | sh
      - name: Login into Okteto
        run: okteto context use https://cloud.okteto.com --token ${{ secrets.OKTETO_TOKEN }}
      - name: Use special namespace
        run: okteto namespace alma-maes95
      - name: Deploy to Okteto
        run: okteto deploy --wait
